import type { NextPage } from "next";
import Head from "next/head";
import { Flow } from "../modules/flow";
import { Palette } from "../modules/palette";
import { Configurator } from "../modules/configurator";
import { Codegen } from "../modules/codegen";
import { DndProvider } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";
import { LayoutGroup } from "framer-motion";

const Home: NextPage = () => {
  return (
    <div className="bg-base-100 h-screen w-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DndProvider backend={HTML5Backend}>
        <main className="w-full h-full relative">
          <div className="w-full h-full fixed z-0">
            <Flow />
          </div>
          <div className="w-full h-full fixed z-10 pointer-events-none">
            <div className="p-8 absolute right-0 flex flex-col items-end gap-2">
              <LayoutGroup>
                <Palette className="pointer-events-none w-fit" />
                <Configurator className="pointer-events-none w-fit" />
                <Codegen className="pointer-events-none w-fit" />
              </LayoutGroup>
            </div>
          </div>
        </main>
      </DndProvider>
    </div>
  );
};

export default Home;
